name: Deploy-Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Next.js App to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy Code and Run Commands on EC2
      - name: Deploy and Run Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            sudo npm install
            sudo npm run build
            sudo fuser -k 3000/tcp || true
            pm2 delete new-app || true
            pm2 start npm --name "new-app" -- start
            pm2 save
            pm2 startup systemd -u ubuntu --hp /home/ubuntu
